"""empty message

Revision ID: 7974745a61f8
Revises: e0e0903c61e8
Create Date: 2019-06-07 21:54:22.512416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7974745a61f8'
down_revision = 'e0e0903c61e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voos', sa.Column('aluno_id', sa.BigInteger(), nullable=False))
    op.add_column('voos', sa.Column('instrutor_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('voos_instrutor_cadastro_fkey', 'voos', type_='foreignkey')
    op.create_foreign_key(None, 'voos', 'alunos', ['aluno_id'], ['num_matric'], ondelete='CASCADE')
    op.create_foreign_key(None, 'voos', 'instrutores', ['instrutor_id'], ['num_cadastro'], ondelete='CASCADE')
    op.drop_column('voos', 'instrutor_cadastro')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voos', sa.Column('instrutor_cadastro', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'voos', type_='foreignkey')
    op.drop_constraint(None, 'voos', type_='foreignkey')
    op.create_foreign_key('voos_instrutor_cadastro_fkey', 'voos', 'instrutores', ['instrutor_cadastro'], ['num_cadastro'], ondelete='CASCADE')
    op.drop_column('voos', 'instrutor_id')
    op.drop_column('voos', 'aluno_id')
    # ### end Alembic commands ###
