"""empty message

Revision ID: e0e0903c61e8
Revises: 
Create Date: 2019-06-07 21:42:33.698144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e0903c61e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('num_matric', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('endereco', sa.String(length=250), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('data_nascimento', sa.String(), nullable=False),
    sa.Column('telefone', sa.BigInteger(), nullable=False),
    sa.Column('total_horas_voo', sa.Integer(), nullable=False),
    sa.Column('data_matric', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('num_matric')
    )
    op.create_table('instrutores',
    sa.Column('num_cadastro', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('endereco', sa.String(length=250), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('data_nascimento', sa.String(), nullable=False),
    sa.Column('telefone', sa.BigInteger(), nullable=False),
    sa.Column('breve', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_cadastro', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('num_cadastro')
    )
    op.create_table('voos',
    sa.Column('num_voo', sa.BigInteger(), nullable=False),
    sa.Column('data_voo', sa.String(), nullable=False),
    sa.Column('data_cadastro', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('hora_inicio', sa.String(), nullable=False),
    sa.Column('horas_total', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('instrutor_cadastro', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['instrutor_cadastro'], ['instrutores.num_cadastro'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('num_voo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voos')
    op.drop_table('instrutores')
    op.drop_table('alunos')
    # ### end Alembic commands ###
