/*
DROP TABLE IF EXISTS user;

CREATE TABLE usuario (
  usuario_id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT NOT NULL,
  cpf TEXT UNIQUE NOT NULL,
  email TEXT NOT NULL,
  senha TEXT NOT NULL
);
*/